load("//bazel:cores.bzl", "cm4_library")

package(default_visibility = ["//visibility:public"])

# Our C++ peripheral wrappers over the generated registers.
cm4_library(
    name = "drivers_new",
    hdrs = glob(["drivers_new/*.hpp"]),
    includes = ["."],
    deps = ["//firmware/cm4/registers"],
)

# Our MPU setup and C++ new/delete.
cm4_library(
    name = "cm4-platform",
    srcs = ["platform/new_delete.cpp"],
    hdrs = ["platform/mpu.hpp"],
    includes = ["."],
    deps = ["//firmware/cm4/registers"],
)
