[tox]
envlist = pytest, lint
isolated_build = true

[flake8]
ignore = E126
max-line-length = 100
indent-size = 2
exclude = scripts/package/.venv

[mypy]
ignore_missing_imports=True
check_untyped_defs = True
cache_dir = ../../.pycache

# Common
[testenv]
passenv = 
    PROJECT_ROOT
    MIMXRT1170EVK_ROOT
    FORGE_ROOT
    ETL_ROOT
    THREADX_ROOT
    NETXDUO_ROOT
    ARM_GCC_TOOLCHAIN_PATH
    CMAKE_PREFIX_PATH
    GTEST_INCLUDE_DIR
    PYTHONPYCACHEPREFIX
    LINK_SERVER
    SERIAL_DEVICE
allowlist_externals = poetry,cmake,flake8,mypy
skip_install = true            # Prevent Tox from trying to install via pip
changedir = scripts/package    # Change to the directory where pyproject.toml is
commands_pre = poetry install  # Install poetry environment in this isolated tox environment

# Unit tests
[testenv:pytest]
deps =
    pytest
    pytest-cov
setenv =
    COVERAGE_FILE = ../../.pycache/.coverage
commands =
    poetry run pytest {toxinidir}/test/pytest/ --cov=mimxrt1170evk {posargs}

# Linting and type checking
[testenv:lint]
commands =
    flake8 --config={toxinidir}/tox.ini {toxinidir}/scripts/package
    mypy --config-file={toxinidir}/tox.ini --package=mimxrt1170evk
