#pragma once

#include <stddef.h>
#include <stdint.h>
#include <cstring>

// // DAC
//
// NOTE: This file was generated from the forge CMSIS-svd wrapper tool.

namespace nDAC {


// Version Identifier Register
//
union VERID {
  
  enum class eFEATURE : uint32_t {
    eFEATURE_0 = 0, // Standard feature set
    eFEATURE_1 = 1, // C40 feature set
    eFEATURE_2 = 2, // 5V DAC feature set
    eFEATURE_4 = 4, // ADC BIST feature set
  };
  
  // Bit field definition.
  struct {
    eFEATURE FEATURE : 16;
    uint32_t MINOR : 8;
    uint32_t MAJOR : 8;
  } bits;
  
  // Full 32-bit register value.
  uint32_t value;

  VERID() = delete;
  inline void Reset() volatile { this->value = 0x01000000; }
  static inline volatile VERID &Instance() { return *reinterpret_cast<volatile VERID*>(0x40064000); }
};

// Parameter Register
//
union PARAM {
  
  enum class eFIFOSZ : uint32_t {
    eFIFOSZ_0 = 0, // FIFO depth is 2
    eFIFOSZ_1 = 1, // FIFO depth is 4
    eFIFOSZ_2 = 2, // FIFO depth is 8
    eFIFOSZ_3 = 3, // FIFO depth is 16
    eFIFOSZ_4 = 4, // FIFO depth is 32
    eFIFOSZ_5 = 5, // FIFO depth is 64
    eFIFOSZ_6 = 6, // FIFO depth is 128
    eFIFOSZ_7 = 7, // FIFO depth is 256
  };
  
  // Bit field definition.
  struct {
    eFIFOSZ FIFOSZ : 3;
    uint32_t _reserved_end : 29;
  } bits;
  
  // Full 32-bit register value.
  uint32_t value;

  PARAM() = delete;
  inline void Reset() volatile { this->value = 0x00000003; }
  static inline volatile PARAM &Instance() { return *reinterpret_cast<volatile PARAM*>(0x40064004); }
};

// DAC Data Register
//
union DATA {
  
  // Bit field definition.
  struct {
    uint32_t DATA0 : 12;
    uint32_t _reserved_end : 20;
  } bits;
  
  // Full 32-bit register value.
  uint32_t value;

  DATA() = delete;
  inline void Reset() volatile { this->value = 0x00000000; }
  static inline volatile DATA &Instance() { return *reinterpret_cast<volatile DATA*>(0x40064008); }
};

// DAC Status and Control Register
//
union CR {
  
  enum class eFULLF : uint32_t {
    eFULLF_0 = 0, // FIFO is not full.
    eFULLF_1 = 1, // FIFO is full.
  };
  
  enum class eNEMPTF : uint32_t {
    eNEMPTF_0 = 0, // More than one data is available in the FIFO.
    eNEMPTF_1 = 1, // One data is available in the FIFO.
  };
  
  enum class eWMF : uint32_t {
    eWMF_0 = 0, // The DAC buffer read pointer has not reached the watermark level.
    eWMF_1 = 1, // The DAC buffer read pointer has reached the watermark level.
  };
  
  enum class eUDFF : uint32_t {
    eUDFF_0 = 0, // No underflow has occurred since the last time the flag was cleared.
    eUDFF_1 = 1, // At least one trigger underflow has occurred since the last time the flag was cleared.
  };
  
  enum class eOVFF : uint32_t {
    eOVFF_0 = 0, // No overflow has occurred since the last time the flag was cleared.
    eOVFF_1 = 1, // At least one FIFO overflow has occurred since the last time the flag was cleared.
  };
  
  enum class eFULLIE : uint32_t {
    eFULLIE_0 = 0, // FIFO Full interrupt is disabled.
    eFULLIE_1 = 1, // FIFO Full interrupt is enabled.
  };
  
  enum class eEMPTIE : uint32_t {
    eEMPTIE_0 = 0, // FIFO Nearly Empty interrupt is disabled.
    eEMPTIE_1 = 1, // FIFO Nearly Empty interrupt is enabled.
  };
  
  enum class eWTMIE : uint32_t {
    eWTMIE_0 = 0, // Watermark interrupt is disabled.
    eWTMIE_1 = 1, // Watermark interrupt is enabled.
  };
  
  enum class eSWTRG : uint32_t {
    eSWTRG_0 = 0, // The DAC soft trigger is not valid.
    eSWTRG_1 = 1, // The DAC soft trigger is valid.
  };
  
  enum class eTRGSEL : uint32_t {
    eTRGSEL_0 = 0, // The DAC hardware trigger is selected.
    eTRGSEL_1 = 1, // The DAC software trigger is selected.
  };
  
  enum class eDACRFS : uint32_t {
    eDACRFS_0 = 0, // The DAC selects DACREF_1 as the reference voltage.
    eDACRFS_1 = 1, // The DAC selects DACREF_2 as the reference voltage.
  };
  
  enum class eDACEN : uint32_t {
    eDACEN_0 = 0, // The DAC system is disabled.
    eDACEN_1 = 1, // The DAC system is enabled.
  };
  
  enum class eFIFOEN : uint32_t {
    eFIFOEN_0 = 0, // FIFO is disabled and only one level buffer is enabled. Any data written from this buffer goes to conversion.
    eFIFOEN_1 = 1, // FIFO is enabled. Data will first read from FIFO to buffer then go to conversion.
  };
  
  enum class eSWMD : uint32_t {
    eSWMD_0 = 0, // Normal mode
    eSWMD_1 = 1, // Swing back mode
  };
  
  enum class eUVIE : uint32_t {
    eUVIE_0 = 0, // Underflow and overflow interrupt is disabled.
    eUVIE_1 = 1, // Underflow and overflow interrupt is enabled.
  };
  
  enum class eFIFORST : uint32_t {
    eFIFORST_0 = 0, // No effect
    eFIFORST_1 = 1, // FIFO reset
  };
  
  enum class eDMAEN : uint32_t {
    eDMAEN_0 = 0, // DMA is disabled.
    eDMAEN_1 = 1, // DMA is enabled. When DMA is enabled, the DMA request will be generated by original interrupts. The interrupts will not be presented on this module at the same time.
  };
  
  // Bit field definition.
  struct {
    eFULLF FULLF : 1;
    eNEMPTF NEMPTF : 1;
    eWMF WMF : 1;
    eUDFF UDFF : 1;
    eOVFF OVFF : 1;
    uint32_t _reserved_5 : 3;
    eFULLIE FULLIE : 1;
    eEMPTIE EMPTIE : 1;
    eWTMIE WTMIE : 1;
    uint32_t _reserved_8 : 1;
    eSWTRG SWTRG : 1;
    eTRGSEL TRGSEL : 1;
    eDACRFS DACRFS : 1;
    eDACEN DACEN : 1;
    eFIFOEN FIFOEN : 1;
    eSWMD SWMD : 1;
    eUVIE UVIE : 1;
    uint32_t _reserved_15 : 2;
    eFIFORST FIFORST : 1;
    uint32_t SWRST : 1;
    eDMAEN DMAEN : 1;
    uint32_t WML : 8;
  } bits;
  
  // Full 32-bit register value.
  uint32_t value;

  CR() = delete;
  inline void Reset() volatile { this->value = 0x00000002; }
  static inline volatile CR &Instance() { return *reinterpret_cast<volatile CR*>(0x4006400C); }
};

// DAC FIFO Pointer Register
//
union PTR {
  
  // Bit field definition.
  struct {
    uint32_t DACWFP : 8;
    uint32_t _reserved_1 : 8;
    uint32_t DACRFP : 8;
    uint32_t _reserved_end : 8;
  } bits;
  
  // Full 32-bit register value.
  uint32_t value;

  PTR() = delete;
  inline void Reset() volatile { this->value = 0x00000000; }
  static inline volatile PTR &Instance() { return *reinterpret_cast<volatile PTR*>(0x40064010); }
};

// DAC Status and Control Register 2
//
union CR2 {
  
  enum class eBFEN : uint32_t {
    eBFEN_0 = 0, // Opamp is not used as buffer
    eBFEN_1 = 1, // Opamp is used as buffer
  };
  
  enum class eOEN : uint32_t {
    eOEN_0 = 0, // Output buffer is not bypassed
    eOEN_1 = 1, // Output buffer is bypassed
  };
  
  enum class eBFMS : uint32_t {
    eBFMS_0 = 0, // Buffer middle speed not selected
    eBFMS_1 = 1, // Buffer middle speed selected
  };
  
  enum class eBFHS : uint32_t {
    eBFHS_0 = 0, // Buffer high speed not selected
    eBFHS_1 = 1, // Buffer high speed selected
  };
  
  enum class eIREF2 : uint32_t {
    eIREF2_0 = 0, // Internal PTAT Current Reference not selected
    eIREF2_1 = 1, // Internal PTAT Current Reference selected
  };
  
  enum class eIREF1 : uint32_t {
    eIREF1_0 = 0, // Internal ZTC Current Reference not selected
    eIREF1_1 = 1, // Internal ZTC Current Reference selected
  };
  
  enum class eIREF : uint32_t {
    eIREF_0 = 0, // Internal Current Reference not selected
    eIREF_1 = 1, // Internal Current Reference selected
  };
  
  // Bit field definition.
  struct {
    eBFEN BFEN : 1;
    eOEN OEN : 1;
    eBFMS BFMS : 1;
    eBFHS BFHS : 1;
    eIREF2 IREF2 : 1;
    eIREF1 IREF1 : 1;
    eIREF IREF : 1;
    uint32_t _reserved_end : 25;
  } bits;
  
  // Full 32-bit register value.
  uint32_t value;

  CR2() = delete;
  inline void Reset() volatile { this->value = 0x00000000; }
  static inline volatile CR2 &Instance() { return *reinterpret_cast<volatile CR2*>(0x40064014); }
};


} // namespace nDAC