load("@forge//bazel:firmware.bzl", "firmware_image")

firmware_image(
    name = "hello-world-cm4",
    srcs = ["hello_world_cm4.cpp"],
    platform = "@forge//bazel/platforms:cm4",
    visibility = ["//visibility:public"],
    deps = [
        "//firmware/cm4:board",
        "//firmware/cm4:cm4-platform",
        "//firmware/cm4:device",
        "//firmware/cm4:drivers",
        "//firmware/cm4:drivers_new",
        "//firmware/cm4:mcmgr",
        "//firmware/cm4:utilities",
        "//firmware/cm4/registers",
        "//firmware/cm4/startup:rt1170-startup-cm4",
    ],
)
