[tool.poetry]
name = "mimxrt1170evk"
version = "0.1.0"
description = ""
authors = ["Jacob <jacob.heathorn@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10" # TODO 3.12?
forge = { path = "<gordion:pyproject:forge/scripts/package>", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
