load("//bazel:cores.bzl", "CORES")

exports_files(["BUILD.arm_gcc"])

# Registers @arm_gcc//:<core> as the C/C++ toolchain whenever the target platform is that core.
[
    toolchain(
        name = core + "_toolchain",
        target_compatible_with = [
            "@platforms//cpu:armv7e-m",
            "@platforms//os:none",
            "//bazel/platforms:" + core + "_core",
        ],
        toolchain = "@arm_gcc//:" + core,
        toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    )
    for core in CORES
]
