load("@forge//bazel:firmware.bzl", "firmware_image")
load("//tools:flash.bzl", "flash")
load("//tools:multicore.bzl", "embedded_image")

embedded_image(
    name = "cm4_image",
    image = "//test/cm4/hello_world:hello-world-cm4",
    platform = "@forge//bazel/platforms:cm4",
    symbol = "hello_world_cm4_bin",
)

firmware_image(
    name = "hello-world-cm7",
    srcs = [
        "hello_world_cm7.cpp",
        ":cm4_image",
    ],
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-shadow",
    ],
    platform = "@forge//bazel/platforms:cm7",
    deps = ["//firmware/cm7:runtime"],
)

flash(
    name = "hello-world-cm7.flash",
    image = ":hello-world-cm7",
)
