load("@forge//bazel:firmware.bzl", "firmware_image")
load("//tools:flash.bzl", "flash")

firmware_image(
    name = "hello-world-cm7",
    srcs = [
        "hello_world_cm7.cpp",
        "//test/cm4/hello_world:hello-world-cm4.bin.cpp",
    ],
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-shadow",
    ],
    platform = "@forge//bazel/platforms:cm7",
    deps = [
        "//firmware/cm7:cm7-platform",
        "//firmware/cm7:utils",
        "//firmware/cm7/legacy:board",
        "//firmware/cm7/legacy:cmsis",
        "//firmware/cm7/legacy:drivers",
        "//firmware/cm7/legacy:mcmgr",
        "//firmware/cm7/legacy:utilities",
        "//firmware/cm7/registers",
        "//firmware/cm7/startup:rt1170-startup-cm7",
    ],
)

flash(
    name = "flash",
    image = ":hello-world-cm7",
)
