include_guard(GLOBAL)
add_subdirectory(
  $ENV{MIMXRT1170EVK_ROOT}/firmware/cm7 
  ${CMAKE_BINARY_DIR}/mimxrt1170evk/firmware
)
add_subdirectory(
  $ENV{MIMXRT1170EVK_ROOT}/test/cm7
  ${CMAKE_BINARY_DIR}/mimxrt1170evk/test
)
