load("@rules_python//python:defs.bzl", "py_binary")

exports_files([
    "console.py",
    "flash.py",
    "on_target_test.py",
])

py_binary(
    name = "console",
    srcs = ["console.py"],
    deps = ["@forge//tools:forge"],
)

py_binary(
    name = "bin_to_cpp",
    srcs = ["bin_to_cpp.py"],
    visibility = ["//visibility:public"],
)
