load("//bazel:cores.bzl", "cm7_library")

# Everything a cm7 image needs to boot and print.
cm7_library(
    name = "runtime",
    visibility = ["//visibility:public"],
    deps = [
        "//mimxrt/cm7/platform",
        "//mimxrt/cm7/registers",
        "//mimxrt/cm7/startup",
        "//mimxrt/cm7/utils",
        "//nxp/cm7:board",
        "//nxp/cm7:cmsis",
        "//nxp/cm7:drivers",
        "//nxp/cm7:mcmgr",
        "//nxp/cm7:utilities",
    ],
)
